// The app bundle's entry point.
//
// This is the whole of the Objective-C in an iOS facet app: `main` hands the
// process to C+, and `facet_gallery_ios_main` never comes back — it calls
// `UIApplicationMain`, which owns the process from there.
//
// There is no AppDelegate.m and no storyboard. facet_uikit synthesizes its own
// delegate class at runtime (`FacetUIKitAppDelegate`) and builds the UIWindow
// in `application:didFinishLaunchingWithOptions:`, so the Info.plist must NOT
// name a storyboard or a scene manifest — see README.md.

#import "facet_gallery_ios.h"   // generated by cpc into target/<triple>/debug/

int main(int argc, char *argv[]) {
    return facet_gallery_ios_main();
}
