// cpc-bindgen ObjC front-end — Objective-C framework header -> C+ wrapper.
//
// Walks `clang -x objective-c -ast-dump=json` for ObjCInterfaceDecl / EnumDecl
// nodes in the target header and emits C+ wrappers calling through the shared
// `objc` runtime (`vendor/objc`): msgSend shims, the str/NSString bridge, the
// `Range` (NSRange) value type, and the +1/`drop` ownership model.
//
// Modelled so far: classes with init / initWith… constructors; instance and
// class methods over void / object / string / scalar / NSRange / enum types;
// nullable string returns -> Option[Text]; NS_ENUM -> C+ enum (+ raw/from_raw);
// NSArray<NSValue *> -> Vec[Range]. Everything else (blocks, multi-arg
// selectors, generic collections) is emitted as a `// SKIPPED` comment rather
// than wrong code. Naming is mechanical snake_case; guideline-level renames are
// a later override file's job.

use std::collections::HashMap;

pub struct ObjcEmitter {
    header_path: String,
    prefix: String,
    body: String,
    needs_vec: bool,
    typedefs: HashMap<String, String>,
    enums: HashMap<String, EnumInfo>,
    used_enums: Vec<String>,
}

#[derive(Clone)]
struct EnumInfo {
    objc_name: String,
    cplus_name: String,
    raw_fn: String,
    from_raw_fn: String,
    variants: Vec<(String, i64)>,
}

enum Ret {
    Void,
    Object,
    Text { nullable: bool },
    ScalarI64,
    ScalarU64,
    EnumTy(String),
    Range,
    ValueArray, // NSArray<NSValue *> -> Vec[Range]
    Unsupported(String),
}

enum Arg {
    Id(String),       // object / string already lowered to an id expression
    ScalarI64(String),
    ScalarU64(String),
    Range(String),
    Unsupported(String),
}

impl ObjcEmitter {
    pub fn new(header_path: &str, prefix: &str) -> Self {
        ObjcEmitter {
            header_path: header_path.to_string(),
            prefix: prefix.to_string(),
            body: String::new(),
            needs_vec: false,
            typedefs: HashMap::new(),
            enums: HashMap::new(),
            used_enums: Vec::new(),
        }
    }

    pub fn run(mut self, tu: &serde_json::Value) -> String {
        let inner = match tu.get("inner").and_then(|v| v.as_array()) {
            Some(a) => a,
            None => return self.preamble(),
        };
        // Pass 1: typedefs (name -> underlying) and NS_ENUM declarations.
        for decl in inner {
            match decl.get("kind").and_then(|v| v.as_str()) {
                Some("TypedefDecl") => {
                    if let (Some(name), Some(under)) = (
                        decl.get("name").and_then(|v| v.as_str()),
                        decl.get("type").and_then(|t| t.get("qualType")).and_then(|v| v.as_str()),
                    ) {
                        self.typedefs.insert(name.to_string(), under.to_string());
                    }
                }
                Some("EnumDecl") => self.collect_enum(decl),
                _ => {}
            }
        }
        // Pass 2: interface wrappers (sticky-file filter excludes builtins).
        let target = base(&self.header_path);
        let mut current_file: Option<String> = None;
        for decl in inner {
            if let Some(loc) = decl.get("loc") {
                if let Some(f) = loc_file(loc) {
                    current_file = Some(f);
                }
            }
            if decl.get("kind").and_then(|v| v.as_str()) != Some("ObjCInterfaceDecl") {
                continue;
            }
            if decl.get("loc").map(loc_included).unwrap_or(false) {
                continue;
            }
            if current_file.as_deref().map(base) == Some(target.clone()) {
                self.emit_interface(decl);
            }
        }

        // Assemble: preamble + the enum defs actually used + interface bodies.
        let mut out = self.preamble();
        for objc_name in self.used_enums.clone() {
            if let Some(info) = self.enums.get(&objc_name).cloned() {
                out.push_str(&self.render_enum(&info));
            }
        }
        out.push_str(&self.body);
        out
    }

    fn preamble(&self) -> String {
        let mut p = String::new();
        p.push_str("// Auto-generated by cpc-bindgen (--objc). DO NOT EDIT.\n");
        p.push_str(&format!("// Source header: {}\n//\n", self.header_path));
        p.push_str("import \"objc/runtime\" as rt;\n");
        p.push_str("import \"objc/bridge\" as bridge;\n");
        p.push_str("import \"stdlib/text\" as text;\n");
        p.push_str("import \"stdlib/option\" as option;\n");
        if self.needs_vec {
            p.push_str("import \"stdlib/vec\" as vec;\n");
        }
        p.push('\n');
        p
    }

    fn collect_enum(&mut self, decl: &serde_json::Value) {
        let objc_name = match decl.get("name").and_then(|v| v.as_str()) {
            Some(n) if !n.is_empty() => n.to_string(),
            _ => return,
        };
        if self.enums.contains_key(&objc_name) {
            return; // clang lists the EnumDecl twice (standalone + typedef'd)
        }
        // Only integer-backed enums; others (rare) are skipped.
        let mut variants: Vec<(String, i64)> = Vec::new();
        let mut next: i64 = 0;
        for c in decl.get("inner").and_then(|v| v.as_array()).cloned().unwrap_or_default() {
            if c.get("kind").and_then(|k| k.as_str()) != Some("EnumConstantDecl") {
                continue;
            }
            let cname = c.get("name").and_then(|n| n.as_str()).unwrap_or("");
            if cname.is_empty() {
                continue;
            }
            let val = read_int(&c).unwrap_or(next);
            let variant = strip_prefix(cname, &objc_name);
            variants.push((pascal(&variant), val));
            next = val + 1;
        }
        if variants.is_empty() {
            return;
        }
        let cplus_name = self.cplus_type_name(&objc_name);
        let snake_name = snake(&cplus_name);
        self.enums.insert(
            objc_name.clone(),
            EnumInfo {
                objc_name,
                cplus_name,
                raw_fn: format!("{snake_name}_raw"),
                from_raw_fn: format!("{snake_name}_from_raw"),
                variants,
            },
        );
    }

    fn render_enum(&self, e: &EnumInfo) -> String {
        let mut s = String::new();
        s.push_str(&format!("// `{}` (NS_ENUM)\n", e.objc_name));
        s.push_str(&format!("enum {} {{\n", e.cplus_name));
        for (v, _) in &e.variants {
            s.push_str(&format!("    {v},\n"));
        }
        s.push_str("}\n\n");
        // raw: enum -> integer
        s.push_str(&format!("fn {}(v: {}) -> i64 {{\n    return match v {{\n", e.raw_fn, e.cplus_name));
        for (v, val) in &e.variants {
            s.push_str(&format!("        {}::{} => {{ {} as i64 }},\n", e.cplus_name, v, val));
        }
        s.push_str("    };\n}\n\n");
        // from_raw: integer -> enum (first variant is the default arm)
        s.push_str(&format!("fn {}(raw: i64) -> {} {{\n", e.from_raw_fn, e.cplus_name));
        for (v, val) in e.variants.iter().skip(1) {
            s.push_str(&format!("    if raw == ({} as i64) {{ return {}::{}; }}\n", val, e.cplus_name, v));
        }
        s.push_str(&format!("    return {}::{};\n}}\n\n", e.cplus_name, e.variants[0].0));
        s
    }

    fn cplus_type_name(&self, objc_name: &str) -> String {
        objc_name.strip_prefix(&self.prefix).unwrap_or(objc_name).to_string()
    }

    fn emit_interface(&mut self, itf: &serde_json::Value) {
        let objc_name = match itf.get("name").and_then(|v| v.as_str()) {
            Some(n) => n.to_string(),
            None => return,
        };
        let ty = self.cplus_type_name(&objc_name);
        let methods: Vec<serde_json::Value> = itf
            .get("inner")
            .and_then(|v| v.as_array())
            .map(|a| a.iter().filter(|m| m.get("kind").and_then(|k| k.as_str()) == Some("ObjCMethodDecl")).cloned().collect())
            .unwrap_or_default();
        let owned = methods.iter().any(|m| {
            let sel = m.get("name").and_then(|v| v.as_str()).unwrap_or("");
            sel == "init" || sel.starts_with("initWith")
        });

        self.body.push_str(&format!(
            "// `{objc_name}` (Foundation/ObjC). Owned via alloc/init; `drop` releases the +1.\n"
        ));
        self.body.push_str(&format!("struct {ty} {{\n    _obj: *u8,\n}}\n\n"));
        self.body.push_str(&format!("impl {ty} {{\n"));
        self.body.push_str("    fn raw(this) -> *u8 { return this._obj; }\n\n");

        let mut init_done = false;
        for m in &methods {
            let sel = m.get("name").and_then(|v| v.as_str()).unwrap_or("").to_string();
            let is_init = sel == "init" || sel.starts_with("initWith");
            if is_init {
                if init_done {
                    self.body.push_str(&format!("    // SKIPPED `{sel}`: extra init variant (one `new` per type)\n"));
                    continue;
                }
                init_done = true;
            }
            self.emit_method(m, &objc_name, &ty, is_init);
        }

        if owned {
            self.body.push_str("    fn drop(ref this) {\n        rt::release(this._obj);\n    }\n");
        }
        self.body.push_str("}\n\n");
    }

    fn emit_method(&mut self, m: &serde_json::Value, objc_class: &str, ty: &str, is_init: bool) {
        let sel = m.get("name").and_then(|v| v.as_str()).unwrap_or("").to_string();
        let is_instance = m.get("instance").and_then(|v| v.as_bool()).unwrap_or(false);
        let ret_qt = m.get("returnType").and_then(|t| t.get("qualType")).and_then(|v| v.as_str()).unwrap_or("void");
        let params: Vec<(String, String)> = m
            .get("inner")
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .filter(|p| p.get("kind").and_then(|k| k.as_str()) == Some("ParmVarDecl"))
                    .map(|p| {
                        (
                            p.get("name").and_then(|n| n.as_str()).unwrap_or("arg").to_string(),
                            p.get("type").and_then(|t| t.get("qualType")).and_then(|v| v.as_str()).unwrap_or("").to_string(),
                        )
                    })
                    .collect()
            })
            .unwrap_or_default();

        if params.len() > 1 {
            self.body.push_str(&format!("    // SKIPPED `{sel}`: {}-arg selectors not yet modelled\n", params.len()));
            return;
        }

        // Lower the single optional argument: `sig_param` is the public C+
        // parameter (the enum/str/Range type), `arg` is the wire expression
        // (the raw int / bridged NSString / etc. passed to msgSend).
        let mut sig_param = String::new();
        let mut arg: Option<Arg> = None;
        if let Some((pname, pqt)) = params.get(0) {
            let pn = snake(pname);
            let a = self.map_arg(pqt, &pn);
            if let Arg::Unsupported(why) = &a {
                self.body.push_str(&format!("    // SKIPPED `{sel}`: param `{pqt}` — {why}\n"));
                return;
            }
            sig_param = format!("{pn}: {}", self.param_sig_type(pqt));
            arg = Some(a);
        }

        // Constructors: alloc + send the init selector, wrap in Self.
        if is_init {
            let send = self.send_expr("alloced", &sel, &Ret::Object, &arg);
            let send = match send {
                Some(s) => s,
                None => {
                    self.body.push_str(&format!("    // SKIPPED `{sel}`: init arg shape not yet modelled\n"));
                    return;
                }
            };
            let header = if sig_param.is_empty() { String::new() } else { sig_param.clone() };
            self.body.push_str(&format!(
                "    fn new({header}) -> {ty} {{\n        let cls: *u8 = rt::get_class(#str_ptr(\"{objc_class}\\0\"));\n        let alloced: *u8 = rt::msg_id(cls, rt::sel(#str_ptr(\"alloc\\0\")));\n        return {ty} {{ _obj: {send} }};\n    }}\n\n"
            ));
            return;
        }

        let ret = self.map_ret(ret_qt);
        if let Ret::Unsupported(why) = &ret {
            self.body.push_str(&format!("    // SKIPPED `{sel}`: return `{ret_qt}` — {why}\n"));
            return;
        }

        let recv = if is_instance {
            "this._obj".to_string()
        } else {
            format!("rt::get_class(#str_ptr(\"{objc_class}\\0\"))")
        };
        let receiver = if is_instance { "this" } else { "" };
        let name = snake(sel.split(':').next().unwrap_or(&sel));

        // ValueArray is a multi-statement body; handle it separately.
        if let Ret::ValueArray = ret {
            let arg = match &arg {
                Some(Arg::Range(e)) => e.clone(),
                _ => {
                    self.body.push_str(&format!("    // SKIPPED `{sel}`: NSArray return needs an NSRange arg\n"));
                    return;
                }
            };
            self.needs_vec = true;
            let sep = if receiver.is_empty() { "" } else { ", " };
            self.body.push_str(&format!(
                "    fn {name}({receiver}{sep}{sig_param}) -> vec::Vec[rt::Range] {{\n\
                 \x20       let arr: *u8 = rt::msg_id_range({recv}, rt::sel(#str_ptr(\"{sel}\\0\")), {arg});\n\
                 \x20       let n: u64 = rt::msg_u64(arr, rt::sel(#str_ptr(\"count\\0\")));\n\
                 \x20       var out: vec::Vec[rt::Range] = vec::Vec[rt::Range]::with_capacity(n as usize);\n\
                 \x20       let at_sel: *u8 = rt::sel(#str_ptr(\"objectAtIndex:\\0\"));\n\
                 \x20       let range_sel: *u8 = rt::sel(#str_ptr(\"rangeValue\\0\"));\n\
                 \x20       var i: u64 = 0 as u64;\n\
                 \x20       while i < n {{\n\
                 \x20           let value: *u8 = rt::msg_id_u64(arr, at_sel, i);\n\
                 \x20           out.append(rt::msg_range(value, range_sel));\n\
                 \x20           i = i +% (1 as u64);\n\
                 \x20       }}\n\
                 \x20       return out;\n    }}\n\n"
            ));
            return;
        }

        let send = match self.send_expr(&recv, &sel, &ret, &arg) {
            Some(s) => s,
            None => {
                self.body.push_str(&format!("    // SKIPPED `{sel}`: (return, arg) shape not yet modelled\n"));
                return;
            }
        };

        let sep = if receiver.is_empty() || sig_param.is_empty() { "" } else { ", " };
        let (ret_spelling, body_line) = match &ret {
            Ret::Void => (String::new(), format!("        {send};\n")),
            Ret::Object => (" -> *u8".into(), format!("        return {send};\n")),
            Ret::ScalarI64 => (" -> i64".into(), format!("        return {send};\n")),
            Ret::ScalarU64 => (" -> u64".into(), format!("        return {send};\n")),
            Ret::Range => (" -> rt::Range".into(), format!("        return {send};\n")),
            Ret::Text { nullable } => {
                if *nullable {
                    (" -> option::Option[text::Text]".into(), format!("        let ns: *u8 = {send};\n        return bridge::to_text_option(ns);\n"))
                } else {
                    (" -> text::Text".into(), format!("        let ns: *u8 = {send};\n        return bridge::to_text(ns);\n"))
                }
            }
            Ret::EnumTy(objc_enum) => {
                let info = self.enums.get(objc_enum).unwrap();
                (format!(" -> {}", info.cplus_name), format!("        return {}({send});\n", info.from_raw_fn))
            }
            Ret::ValueArray | Ret::Unsupported(_) => unreachable!(),
        };

        self.body.push_str(&format!("    fn {name}({receiver}{sep}{sig_param}){ret_spelling} {{\n{body_line}    }}\n\n"));
    }

    /// The `rt::msg_*` call expression for a (receiver, selector, return, arg)
    /// combination, or None if no runtime shape covers it. For enum returns the
    /// raw integer call is produced (the caller wraps it in `<enum>_from_raw`).
    fn send_expr(&mut self, recv: &str, sel: &str, ret: &Ret, arg: &Option<Arg>) -> Option<String> {
        let sl = format!("rt::sel(#str_ptr(\"{sel}\\0\"))");
        // Reduce the return to a wire class: id-like, i64-like, u64-like, range, void.
        enum Wire { Id, I64, U64, Range, Void }
        let wire = match ret {
            Ret::Void => Wire::Void,
            Ret::Object | Ret::Text { .. } => Wire::Id,
            Ret::ScalarI64 | Ret::EnumTy(_) => Wire::I64,
            Ret::ScalarU64 => Wire::U64,
            Ret::Range => Wire::Range,
            Ret::ValueArray | Ret::Unsupported(_) => return None,
        };
        let a = arg.as_ref();
        let expr = match (wire, a) {
            (Wire::Void, None) => format!("rt::msg_void({recv}, {sl})"),
            (Wire::Void, Some(Arg::Id(e))) => format!("rt::msg_void_id({recv}, {sl}, {e})"),
            (Wire::Id, None) => format!("rt::msg_id({recv}, {sl})"),
            (Wire::Id, Some(Arg::Id(e))) => format!("rt::msg_id_id({recv}, {sl}, {e})"),
            (Wire::Id, Some(Arg::ScalarI64(e))) => format!("rt::msg_id_i64({recv}, {sl}, {e})"),
            (Wire::Id, Some(Arg::ScalarU64(e))) => format!("rt::msg_id_u64({recv}, {sl}, {e})"),
            (Wire::Id, Some(Arg::Range(e))) => format!("rt::msg_id_range({recv}, {sl}, {e})"),
            (Wire::I64, None) => format!("rt::msg_i64({recv}, {sl})"),
            (Wire::U64, None) => format!("rt::msg_u64({recv}, {sl})"),
            (Wire::Range, None) => format!("rt::msg_range({recv}, {sl})"),
            (Wire::Range, Some(Arg::ScalarU64(e))) => format!("rt::msg_range_u64({recv}, {sl}, {e})"),
            (Wire::Range, Some(Arg::Range(e))) => format!("rt::msg_range_range({recv}, {sl}, {e})"),
            _ => return None,
        };
        Some(expr)
    }

    fn map_ret(&mut self, qt: &str) -> Ret {
        let (base_ty, nullable) = strip_nullability(qt);
        let base_ty = base_ty.trim();
        if base_ty == "void" {
            return Ret::Void;
        }
        if base_ty == "NSRange" {
            return Ret::Range;
        }
        if self.is_value_array(base_ty) {
            return Ret::ValueArray;
        }
        if self.is_nsstring(base_ty) {
            return Ret::Text { nullable };
        }
        if let Some(objc_enum) = self.enum_of(base_ty) {
            if !self.used_enums.contains(&objc_enum) {
                self.used_enums.push(objc_enum.clone());
            }
            return Ret::EnumTy(objc_enum);
        }
        match base_ty {
            "NSInteger" | "long" => return Ret::ScalarI64,
            "NSUInteger" | "unsigned long" => return Ret::ScalarU64,
            "instancetype" => return Ret::Object,
            "id" => return Ret::Object,
            // 32-bit / float scalars need their own msgSend widths; defer.
            "int" | "unsigned int" | "unsigned" | "double" | "float" => {
                return Ret::Unsupported(format!("scalar `{base_ty}` not yet modelled"))
            }
            _ => {}
        }
        if base_ty.contains('<') {
            return Ret::Unsupported("generic collection".into());
        }
        if base_ty.contains('^') {
            return Ret::Unsupported("block".into());
        }
        if base_ty.ends_with('*') {
            return Ret::Object;
        }
        Ret::Unsupported(format!("unmapped type `{base_ty}`"))
    }

    fn map_arg(&mut self, qt: &str, pname: &str) -> Arg {
        let (base_ty, _) = strip_nullability(qt);
        let base_ty = base_ty.trim();
        if base_ty == "NSRange" {
            return Arg::Range(pname.to_string());
        }
        if self.is_nsstring(base_ty) {
            return Arg::Id(format!("bridge::nsstring({pname})"));
        }
        if let Some(objc_enum) = self.enum_of(base_ty) {
            if !self.used_enums.contains(&objc_enum) {
                self.used_enums.push(objc_enum.clone());
            }
            let raw = self.enums.get(&objc_enum).unwrap().raw_fn.clone();
            return Arg::ScalarI64(format!("{raw}({pname})"));
        }
        match base_ty {
            "NSInteger" | "long" => return Arg::ScalarI64(pname.to_string()),
            "NSUInteger" | "unsigned long" => return Arg::ScalarU64(pname.to_string()),
            "id" => return Arg::Id(pname.to_string()),
            "int" | "unsigned int" | "unsigned" | "double" | "float" => {
                return Arg::Unsupported(format!("scalar `{base_ty}` not yet modelled"))
            }
            _ => {}
        }
        if base_ty.contains('^') {
            return Arg::Unsupported("block".into());
        }
        if base_ty.contains('<') {
            return Arg::Unsupported("generic collection".into());
        }
        if base_ty.ends_with('*') {
            return Arg::Id(pname.to_string());
        }
        Arg::Unsupported(format!("unmapped type `{base_ty}`"))
    }

    /// The public C+ parameter type for an ObjC param spelling (str / Range /
    /// the enum type / a scalar / a raw object handle).
    fn param_sig_type(&self, qt: &str) -> String {
        let (b, _) = strip_nullability(qt);
        let b = b.trim();
        if b == "NSRange" {
            return "rt::Range".to_string();
        }
        if self.is_nsstring(b) {
            return "str".to_string();
        }
        if let Some(objc_enum) = self.enum_of(b) {
            return self.enums.get(&objc_enum).unwrap().cplus_name.clone();
        }
        match b {
            "NSInteger" | "long" => "i64".to_string(),
            "NSUInteger" | "unsigned long" => "u64".to_string(),
            "int" => "i32".to_string(),
            "unsigned int" | "unsigned" => "u32".to_string(),
            _ => "*u8".to_string(),
        }
    }

    fn enum_of(&self, ty: &str) -> Option<String> {
        if self.enums.contains_key(ty) {
            return Some(ty.to_string());
        }
        // Follow typedefs to an enum name.
        let mut cur = ty.to_string();
        for _ in 0..8 {
            if self.enums.contains_key(&cur) {
                return Some(cur);
            }
            match self.typedefs.get(&cur) {
                Some(u) => cur = u.trim().to_string(),
                None => return None,
            }
        }
        None
    }

    fn is_value_array(&self, ty: &str) -> bool {
        let t = ty.replace(' ', "");
        t == "NSArray<NSValue*>*"
    }

    fn is_nsstring(&self, ty: &str) -> bool {
        let t = ty.trim();
        if t == "NSString *" || t == "NSString*" {
            return true;
        }
        let mut cur = t.to_string();
        for _ in 0..8 {
            match self.typedefs.get(&cur) {
                Some(under) => {
                    let u = under.trim();
                    if u == "NSString *" || u == "NSString*" {
                        return true;
                    }
                    cur = u.to_string();
                }
                None => return false,
            }
        }
        false
    }
}

fn base(p: &str) -> String {
    std::path::Path::new(p).file_name().map(|s| s.to_string_lossy().to_string()).unwrap_or_default()
}

/// clang's `loc` puts the file directly, or (for macro-expanded decls like
/// NS_ENUM) under `expansionLoc`/`spellingLoc`. Prefer the expansion site.
fn loc_file(loc: &serde_json::Value) -> Option<String> {
    loc.get("file")
        .and_then(|f| f.as_str())
        .or_else(|| loc.get("expansionLoc").and_then(|e| e.get("file")).and_then(|f| f.as_str()))
        .or_else(|| loc.get("spellingLoc").and_then(|e| e.get("file")).and_then(|f| f.as_str()))
        .map(|s| s.to_string())
}

/// True if the decl came in via an #include/#import (so it isn't ours).
fn loc_included(loc: &serde_json::Value) -> bool {
    loc.get("includedFrom").is_some()
        || loc.get("expansionLoc").and_then(|e| e.get("includedFrom")).is_some()
}

fn strip_nullability(qt: &str) -> (String, bool) {
    let s = qt.trim();
    for (suf, nul) in [(" _Nullable", true), (" _Nonnull", false), (" _Null_unspecified", true)] {
        if let Some(stripped) = s.strip_suffix(suf) {
            return (stripped.to_string(), nul);
        }
    }
    (s.to_string(), false)
}

/// Strip a leading enum-name prefix from a constant (NLTokenUnitWord -> Word).
fn strip_prefix(name: &str, enum_name: &str) -> String {
    name.strip_prefix(enum_name).filter(|s| !s.is_empty()).unwrap_or(name).to_string()
}

fn pascal(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
        None => String::new(),
    }
}

/// Read an explicit integer value from an EnumConstantDecl's initializer.
fn read_int(node: &serde_json::Value) -> Option<i64> {
    fn search(v: &serde_json::Value) -> Option<i64> {
        if let Some(s) = v.get("value").and_then(|x| x.as_str()) {
            if let Ok(n) = s.parse::<i64>() {
                return Some(n);
            }
        }
        for c in v.get("inner").and_then(|x| x.as_array()).into_iter().flatten() {
            if let Some(n) = search(c) {
                return Some(n);
            }
        }
        None
    }
    node.get("inner").and_then(|x| x.as_array()).into_iter().flatten().find_map(search)
}

/// camelCase / PascalCase -> snake_case.
fn snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
