// cpc-bindgen ObjC front-end — Objective-C framework header -> C+ wrapper.
//
// Walks `clang -x objective-c -ast-dump=json` for ObjCInterfaceDecl nodes in the
// target header and emits a C+ wrapper struct + `impl` per class, calling
// through the shared `objc` runtime (`vendor/objc`): msgSend shims, the
// str/NSString bridge, and the +1/`drop` ownership model.
//
// MVP scope (the NaturalLanguage golden target): classes with an `init`, plain
// instance/class methods over `void` / object / string / scalar types, and
// nullable string returns mapped to `Option[Text]`. Anything else (collections,
// blocks, structs, multi-arg shapes not yet modelled) is emitted as a
// `// SKIPPED` comment rather than wrong code. Naming is mechanical snake_case;
// guideline-level renames (role types, semantic names, defaults) are the job of
// a later override file.

use std::collections::HashMap;

pub struct ObjcEmitter {
    header_path: String,
    prefix: String,
    out: String,
    typedefs: HashMap<String, String>,
}

enum Mapped {
    Void,
    SelfTy,
    Object,
    StrParam,
    TextRet { nullable: bool },
    Scalar(&'static str),
    Unsupported(String),
}

impl ObjcEmitter {
    pub fn new(header_path: &str, prefix: &str) -> Self {
        let mut out = String::new();
        out.push_str("// Auto-generated by cpc-bindgen (--objc). DO NOT EDIT.\n");
        out.push_str(&format!("// Source header: {header_path}\n//\n"));
        out.push_str("import \"objc/runtime\" as rt;\n");
        out.push_str("import \"objc/bridge\" as bridge;\n");
        out.push_str("import \"stdlib/text\" as text;\n");
        out.push_str("import \"stdlib/option\" as option;\n\n");
        ObjcEmitter {
            header_path: header_path.to_string(),
            prefix: prefix.to_string(),
            out,
            typedefs: HashMap::new(),
        }
    }

    pub fn run(mut self, tu: &serde_json::Value) -> String {
        let inner = match tu.get("inner").and_then(|v| v.as_array()) {
            Some(a) => a,
            None => return self.out,
        };
        // Pass 1: collect every typedef name -> underlying spelling (whole TU,
        // including system headers) so `NLLanguage` resolves to `NSString *`.
        for decl in inner {
            if decl.get("kind").and_then(|v| v.as_str()) == Some("TypedefDecl") {
                if let (Some(name), Some(under)) = (
                    decl.get("name").and_then(|v| v.as_str()),
                    decl.get("type").and_then(|t| t.get("qualType")).and_then(|v| v.as_str()),
                ) {
                    self.typedefs.insert(name.to_string(), under.to_string());
                }
            }
        }
        // Pass 2: emit a wrapper per ObjCInterfaceDecl declared in this header.
        // clang sets `loc.file` only on the first decl of each file and elides
        // it on following same-file siblings, so track it stickily; a decl
        // belongs to whatever file was last seen. Builtins (Protocol, OS_object,
        // ...) appear before the main file's first decl, so they never match.
        let target = base(&self.header_path);
        let mut current_file: Option<String> = None;
        for decl in inner {
            if let Some(f) = decl.get("loc").and_then(|l| l.get("file")).and_then(|f| f.as_str()) {
                current_file = Some(f.to_string());
            }
            if decl.get("kind").and_then(|v| v.as_str()) != Some("ObjCInterfaceDecl") {
                continue;
            }
            // Decls pulled in by an #import carry `includedFrom`; skip those.
            if decl.get("loc").and_then(|l| l.get("includedFrom")).is_some() {
                continue;
            }
            if current_file.as_deref().map(base) == Some(target.clone()) {
                self.emit_interface(decl);
            }
        }
        self.out
    }

    fn cplus_type_name(&self, objc_name: &str) -> String {
        objc_name.strip_prefix(&self.prefix).unwrap_or(objc_name).to_string()
    }

    fn emit_interface(&mut self, itf: &serde_json::Value) {
        let objc_name = match itf.get("name").and_then(|v| v.as_str()) {
            Some(n) => n.to_string(),
            None => return,
        };
        let ty = self.cplus_type_name(&objc_name);
        let methods: Vec<&serde_json::Value> = itf
            .get("inner")
            .and_then(|v| v.as_array())
            .map(|a| a.iter().filter(|m| m.get("kind").and_then(|k| k.as_str()) == Some("ObjCMethodDecl")).collect())
            .unwrap_or_default();
        let owned = methods.iter().any(|m| {
            let sel = m.get("name").and_then(|v| v.as_str()).unwrap_or("");
            sel == "init" || sel.starts_with("initWith")
        });

        self.out.push_str(&format!(
            "// `{objc_name}` (Foundation/ObjC). Owned via alloc/init; `drop` releases the +1.\n"
        ));
        self.out.push_str(&format!("struct {ty} {{\n    _obj: *u8,\n}}\n\n"));
        self.out.push_str(&format!("impl {ty} {{\n"));
        self.out.push_str("    fn raw(this) -> *u8 { return this._obj; }\n\n");

        for m in &methods {
            self.emit_method(m, &objc_name, &ty);
        }

        if owned {
            self.out.push_str("    fn drop(ref this) {\n        rt::release(this._obj);\n    }\n");
        }
        self.out.push_str("}\n\n");
    }

    fn emit_method(&mut self, m: &serde_json::Value, objc_class: &str, ty: &str) {
        let sel = m.get("name").and_then(|v| v.as_str()).unwrap_or("").to_string();
        let is_instance = m.get("instance").and_then(|v| v.as_bool()).unwrap_or(false);
        let ret_qt = m.get("returnType").and_then(|t| t.get("qualType")).and_then(|v| v.as_str()).unwrap_or("void");

        let params: Vec<(String, String)> = m
            .get("inner")
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .filter(|p| p.get("kind").and_then(|k| k.as_str()) == Some("ParmVarDecl"))
                    .map(|p| {
                        (
                            p.get("name").and_then(|n| n.as_str()).unwrap_or("arg").to_string(),
                            p.get("type").and_then(|t| t.get("qualType")).and_then(|v| v.as_str()).unwrap_or("").to_string(),
                        )
                    })
                    .collect()
            })
            .unwrap_or_default();

        // `init` family -> a `new` constructor.
        if sel == "init" && is_instance {
            self.out.push_str(&format!(
                "    fn new() -> {ty} {{\n        return {ty} {{ _obj: rt::alloc_init(#str_ptr(\"{objc_class}\\0\")) }};\n    }}\n\n"
            ));
            return;
        }

        let parts: Vec<&str> = sel.split(':').filter(|s| !s.is_empty()).collect();
        if parts.len() != params.len() && !params.is_empty() {
            self.out.push_str(&format!("    // SKIPPED `{sel}`: selector/param arity mismatch\n"));
            return;
        }
        // MVP supports 0- and 1-argument selectors.
        if params.len() > 1 {
            self.out.push_str(&format!("    // SKIPPED `{sel}`: {}-arg selectors not yet modelled\n", params.len()));
            return;
        }

        let ret = self.map(ret_qt, true);
        if let Mapped::Unsupported(why) = &ret {
            self.out.push_str(&format!("    // SKIPPED `{sel}`: return `{ret_qt}` — {why}\n"));
            return;
        }

        let name = snake(parts.get(0).copied().unwrap_or(&sel));
        let recv = if is_instance { "this._obj".to_string() } else { format!("rt::get_class(#str_ptr(\"{objc_class}\\0\"))") };
        let receiver_param = if is_instance { "this" } else { "" };

        // Build the one optional argument.
        let mut sig_params = String::new();
        let mut arg_expr: Option<String> = None;
        if let Some((pname, pqt)) = params.get(0) {
            let pm = self.map(pqt, false);
            match pm {
                Mapped::StrParam => {
                    let pn = snake(pname);
                    sig_params = format!(", {pn}: str");
                    arg_expr = Some(format!("bridge::nsstring({pn})"));
                }
                Mapped::Object => {
                    let pn = snake(pname);
                    sig_params = format!(", {pn}: *u8");
                    arg_expr = Some(pn);
                }
                Mapped::Scalar(t) => {
                    let pn = snake(pname);
                    sig_params = format!(", {pn}: {t}");
                    arg_expr = Some(pn);
                }
                _ => {
                    self.out.push_str(&format!("    // SKIPPED `{sel}`: param `{pqt}` not yet modelled\n"));
                    return;
                }
            }
        }

        // Pick the msgSend wrapper + return spelling/body from the return type.
        let sel_lit = format!("rt::sel(#str_ptr(\"{sel}\\0\"))");
        let (ret_spelling, body): (String, String) = match (&ret, arg_expr.as_ref()) {
            (Mapped::Void, None) => (String::new(), format!("        rt::msg_void({recv}, {sel_lit});\n")),
            (Mapped::Void, Some(a)) => (String::new(), format!("        rt::msg_void_id({recv}, {sel_lit}, {a});\n")),
            (Mapped::Object, None) => (" -> *u8".to_string(), format!("        return rt::msg_id({recv}, {sel_lit});\n")),
            (Mapped::Object, Some(a)) => (" -> *u8".to_string(), format!("        return rt::msg_id_id({recv}, {sel_lit}, {a});\n")),
            (Mapped::TextRet { nullable }, arg) => {
                let call = match arg {
                    None => format!("rt::msg_id({recv}, {sel_lit})"),
                    Some(a) => format!("rt::msg_id_id({recv}, {sel_lit}, {a})"),
                };
                if *nullable {
                    (" -> option::Option[text::Text]".to_string(), format!("        let ns: *u8 = {call};\n        return bridge::to_text_option(ns);\n"))
                } else {
                    (" -> text::Text".to_string(), format!("        let ns: *u8 = {call};\n        return bridge::to_text(ns);\n"))
                }
            }
            (Mapped::Scalar(_), _) | (Mapped::SelfTy, _) | (Mapped::Unsupported(_), _) | (Mapped::StrParam, _) => {
                self.out.push_str(&format!("    // SKIPPED `{sel}`: return shape not yet modelled\n"));
                return;
            }
        };

        let comma = if receiver_param.is_empty() && !sig_params.is_empty() {
            // static method with a param: drop the leading ", "
            sig_params = sig_params.trim_start_matches(", ").to_string();
            ""
        } else {
            ""
        };
        let _ = comma;
        self.out.push_str(&format!("    fn {name}({receiver_param}{sig_params}){ret_spelling} {{\n{body}    }}\n\n"));
    }

    /// Resolve a possibly-typedef'd ObjC type spelling to a C+ mapping.
    fn map(&self, qt: &str, is_return: bool) -> Mapped {
        let (base_ty, nullable) = strip_nullability(qt);
        let base_ty = base_ty.trim();
        if base_ty == "void" {
            return Mapped::Void;
        }
        if base_ty == "instancetype" {
            return Mapped::SelfTy;
        }
        // Strings: NSString* directly, or a typedef that resolves to NSString*.
        if self.is_nsstring(base_ty) {
            return if is_return { Mapped::TextRet { nullable } } else { Mapped::StrParam };
        }
        match base_ty {
            "NSInteger" => return Mapped::Scalar("i64"),
            "NSUInteger" => return Mapped::Scalar("u64"),
            "double" => return Mapped::Scalar("f64"),
            "float" => return Mapped::Scalar("f32"),
            "int" => return Mapped::Scalar("i32"),
            "unsigned int" | "unsigned" => return Mapped::Scalar("u32"),
            "long" => return Mapped::Scalar("i64"),
            _ => {}
        }
        // Generic ObjC object pointer (id, NSObject*, etc.) but NOT a generic
        // collection (those need element handling we don't do yet).
        if base_ty == "id" {
            return Mapped::Object;
        }
        if base_ty.contains('<') {
            return Mapped::Unsupported("generic collection".into());
        }
        if base_ty.ends_with('*') {
            return Mapped::Object;
        }
        Mapped::Unsupported(format!("unmapped type `{base_ty}`"))
    }

    fn is_nsstring(&self, ty: &str) -> bool {
        let t = ty.trim();
        if t == "NSString *" || t == "NSString*" {
            return true;
        }
        // Follow a chain of typedefs (e.g. NLLanguage -> NSString *).
        let mut cur = t.to_string();
        for _ in 0..8 {
            match self.typedefs.get(&cur) {
                Some(under) => {
                    let u = under.trim();
                    if u == "NSString *" || u == "NSString*" {
                        return true;
                    }
                    cur = u.to_string();
                }
                None => return false,
            }
        }
        false
    }
}

fn base(p: &str) -> String {
    std::path::Path::new(p)
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_default()
}

/// Split a trailing ` _Nullable` / ` _Nonnull` off a type spelling.
fn strip_nullability(qt: &str) -> (String, bool) {
    let s = qt.trim();
    if let Some(stripped) = s.strip_suffix(" _Nullable") {
        return (stripped.to_string(), true);
    }
    if let Some(stripped) = s.strip_suffix(" _Nonnull") {
        return (stripped.to_string(), false);
    }
    if let Some(stripped) = s.strip_suffix(" _Null_unspecified") {
        return (stripped.to_string(), true);
    }
    (s.to_string(), false)
}

/// camelCase / PascalCase ObjC selector segment -> snake_case C+ identifier.
fn snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
