//! WinMD -> C+ projection. Metadata is read by Microsoft's ECMA-335 reader.
//! The handwritten winrt runtime is independent of both WinUI and Facet.
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
use std::path::PathBuf;
use sha1::{Digest, Sha1};
use windows_metadata::{HasAttributes, File, Item, MethodDef, ParamAttributes, Reader, Type, TypeDef, TypeKind, TypeName, Value};

type Fallible<T> = Result<T, String>;

pub fn run(args: &[String]) -> Fallible<()> {
    let mut inputs = Vec::new();
    let mut includes = Vec::new();
    let mut output = None;
    let mut package = "winui".to_string();
    let mut i = 0;
    while i < args.len() {
        let flag = &args[i];
        let value = args.get(i + 1).ok_or_else(|| format!("missing value after {flag}"))?;
        match flag.as_str() {
            "--winmd" | "--reference" => inputs.push(PathBuf::from(value)),
            "--include" => includes.push(value.clone()),
            "--out" => output = Some(PathBuf::from(value)),
            "--package" => package = value.clone(),
            "--selection" => {
                let data = std::fs::read_to_string(value).map_err(|e| format!("{value}: {e}"))?;
                let selected: serde_json::Value = serde_json::from_str(&data).map_err(|e| e.to_string())?;
                let types = selected["include"].as_array().ok_or("selection needs an include array")?;
                for ty in types { includes.push(ty.as_str().ok_or("include must contain strings")?.into()); }
            }
            _ => return Err(format!("unknown option {flag}; use --winmd FILE --reference FILE --selection FILE --out DIR --package NAME")),
        }
        i += 2;
    }
    let output = output.ok_or("--out DIR is required")?;
    if includes.is_empty() { return Err("--include TYPE or --selection FILE is required (namespaces end in .*)".into()); }
    if !identifier(&package) { return Err("package must be a C+ identifier".into()); }
    let mut files = Vec::new();
    let mut sources = Vec::new();
    for input in &inputs {
        let bytes = std::fs::read(input).map_err(|e| format!("{}: {e}", input.display()))?;
        sources.push(serde_json::json!({"file":input.file_name().unwrap().to_string_lossy(), "sha1":format!("{:x}", Sha1::digest(&bytes))}));
        files.push(File::new(bytes).ok_or_else(|| format!("{} is not valid WinMD",input.display()))?);
    }
    // The reader intentionally owns process-lifetime metadata. It may panic on
    // unresolved references; report that as an input error, never partial output.
    let generated = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let reader = Reader::new(files);
        Generator::new(reader).generate(&includes, &package)
    })).map_err(|_| "metadata resolution failed; provide all referenced WinMD files".to_string())??;
    std::fs::create_dir_all(output.join("src")).map_err(|e| e.to_string())?;
    std::fs::write(output.join("src").join(format!("{package}.cplus")), &generated.0).map_err(|e| e.to_string())?;
    let manifest = serde_json::json!({"generator":"cpc-bindgen --winmd", "version":env!("CARGO_PKG_VERSION"),
        "target":"windows-x64", "sources":sources, "include":includes, "types":generated.1});
    std::fs::write(output.join("MANIFEST.json"), serde_json::to_string_pretty(&manifest).unwrap()+"\n").map_err(|e| e.to_string())?;
    std::fs::write(output.join("Cplus.toml"), format!("# Auto-generated by cpc-bindgen --winmd.\n# Inputs and selection: MANIFEST.json. Repository reproduction: tools/generate_winui.ps1.\n[package]\nname = \"{package}\"\nversion = \"0.0.1\"\nedition = \"2026\"\n\n[dependencies]\nstdlib = \"*\"\nwinrt = \"*\"\n")).map_err(|e| e.to_string())?;
    println!("generated {} metadata types into {}", generated.1.len(), output.display());
    Ok(())
}

fn identifier(s: &str) -> bool { !s.is_empty() && s.chars().enumerate().all(|(i,c)| c=='_' || c.is_ascii_alphabetic() || (i>0 && c.is_ascii_digit())) }
fn full(def: TypeDef) -> String { format!("{}.{}",def.namespace(),def.name()) }
fn snake(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let mut out = String::new();
    for (i,&c) in chars.iter().enumerate() {
        if c.is_ascii_uppercase() && i>0 && (chars[i-1].is_ascii_lowercase() || chars[i-1].is_ascii_digit() || (i+1<chars.len() && chars[i+1].is_ascii_lowercase() && chars[i-1].is_ascii_uppercase())) { out.push('_'); }
        out.push(if c.is_ascii_alphanumeric() || c=='_' { c.to_ascii_lowercase() } else { '_' });
    }
    while out.contains("__") { out=out.replace("__","_"); }
    out=out.trim_matches('_').to_string();
    if ["type","ref","take","move","this","self","match","loop","in","as","fn","return","default","new","clone","drop","raw","object","query","iid","let","var","const","static","struct","enum","impl","interface","import","export","extern","if","else","for","while","break","continue","defer","gen","yield","async","await","guard","true","false","null","unsafe","where","restrict","opaque"].contains(&out.as_str()) { out.push_str("_value"); }
    out
}
fn method_name(method: MethodDef) -> String {
    if let Some(attribute)=method.find_attribute("OverloadAttribute") {
        if let Some((_,Value::String(value)))=attribute.args().first() { return value.clone(); }
    }
    method.name().to_string()
}
fn attrs(def: TypeDef, name: &str) -> Vec<Vec<Value>> {
    def.attributes().filter(|a|a.name()==name).map(|a|a.args().into_iter().map(|(_,v)|v).collect()).collect()
}
fn number(value: &Value) -> Fallible<u64> {
    match value { Value::U8(v)=>Ok(*v as u64),Value::U16(v)=>Ok(*v as u64),Value::U32(v)=>Ok(*v as u64),Value::I32(v)=>Ok(*v as u32 as u64),Value::U64(v)=>Ok(*v),Value::EnumDef(_,v)=>number(v),_=>Err("expected numeric metadata value".into()) }
}
fn guid(def: TypeDef) -> Fallible<[u8;16]> {
    let values = attrs(def,"GuidAttribute").into_iter().next().ok_or_else(||format!("{} has no GUID",full(def)))?;
    if values.len()!=11 { return Err("invalid GuidAttribute".into()); }
    let mut b=[0;16]; b[..4].copy_from_slice(&(number(&values[0])? as u32).to_be_bytes());
    b[4..6].copy_from_slice(&(number(&values[1])? as u16).to_be_bytes()); b[6..8].copy_from_slice(&(number(&values[2])? as u16).to_be_bytes());
    for i in 0..8 { b[8+i]=number(&values[3+i])? as u8; } Ok(b)
}
fn guid_string(b: &[u8;16]) -> String {
    format!("{:08x}-{:04x}-{:04x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}",u32::from_be_bytes(b[..4].try_into().unwrap()),u16::from_be_bytes(b[4..6].try_into().unwrap()),u16::from_be_bytes(b[6..8].try_into().unwrap()),b[8],b[9],b[10],b[11],b[12],b[13],b[14],b[15])
}
fn guid_literal(b: &[u8;16]) -> String {
    format!("rt::Guid {{ a: {}u32, b: {} as u16, c: {} as u16, d: [{}] }}",u32::from_be_bytes(b[..4].try_into().unwrap()),u16::from_be_bytes(b[4..6].try_into().unwrap()),u16::from_be_bytes(b[6..8].try_into().unwrap()),b[8..].iter().map(|v|format!("{v} as u8")).collect::<Vec<_>>().join(", "))
}
fn parameterized(signature: &str) -> [u8;16] {
    let namespace=[0x11,0xf4,0x7a,0xd5,0x7b,0x73,0x42,0xc0,0xab,0xae,0x87,0x8b,0x1e,0x16,0xad,0xee];
    let mut hash=Sha1::new(); hash.update(namespace); hash.update(signature.as_bytes());
    let digest=hash.finalize(); let mut result=[0;16]; result.copy_from_slice(&digest[..16]);
    result[6]=(result[6]&15)|0x50; result[8]=(result[8]&63)|0x80; result
}

struct Generator {
    reader: &'static Reader,
    types: BTreeMap<String,Type>,
    names: BTreeMap<String,String>,
    reports: Vec<serde_json::Value>,
}
impl Generator {
    fn new(reader: &'static Reader) -> Self { Self { reader,types:BTreeMap::new(),names:BTreeMap::new(),reports:Vec::new() } }
    fn resolve(&self, name: TypeName) -> Fallible<TypeDef> {
        self.reader.get_type_def(name.0,name.1).next().ok_or_else(||format!("missing {}.{}; add its WinMD with --reference",name.0,name.1))
    }
    fn key(ty: &Type) -> String {
        match ty {
            Type::TypeDef(d,g) if !g.is_empty()=>format!("{}<{}>",full(*d),g.iter().map(Self::key).collect::<Vec<_>>().join(",")),
            Type::TypeDef(d,_)=>full(*d), Type::Name(n)=>format!("{}.{}",n.0,n.1), _=>format!("{ty:?}"),
        }
    }
    fn default(&self, d: TypeDef) -> Fallible<Type> {
        d.interface_impls().find(|i|i.has_attribute("DefaultAttribute")).map(|i|i.ty(&[])).ok_or_else(||format!("{} has no default interface",full(d)))
    }
    fn signature(&self, ty: &Type) -> Fallible<String> {
        Ok(match ty {
            Type::Bool=>"b1".into(),Type::U8=>"u1".into(),Type::I16=>"i2".into(),Type::U16=>"u2".into(),Type::I32=>"i4".into(),Type::U32=>"u4".into(),Type::I64=>"i8".into(),Type::U64=>"u8".into(),Type::F32=>"f4".into(),Type::F64=>"f8".into(),Type::Char=>"c2".into(),Type::String=>"string".into(),Type::Object=>"cinterface(IInspectable)".into(),Type::Name(TypeName::GUID)=>"g16".into(),
            Type::TypeDef(d,g) => match d.kind() {
                TypeKind::Interface|TypeKind::Delegate if !g.is_empty()=>format!("pinterface({{{}}};{})",guid_string(&guid(*d)?),g.iter().map(|t|self.signature(t)).collect::<Fallible<Vec<_>>>()?.join(";")),
                TypeKind::Interface=>format!("{{{}}}",guid_string(&guid(*d)?)),
                TypeKind::Delegate=>format!("delegate({{{}}})",guid_string(&guid(*d)?)),
                TypeKind::Class=>format!("rc({};{})",full(*d),self.signature(&self.default(*d)?)?),
                TypeKind::Enum=>format!("enum({};{})",full(*d),self.signature(&d.underlying_type())?),
                TypeKind::Struct=>format!("struct({};{})",full(*d),d.fields().map(|f|self.signature(&f.ty(Some(*d)))).collect::<Fallible<Vec<_>>>()?.join(";")),
            },
            _=>return Err(format!("no WinRT type signature for {ty:?}")),
        })
    }
    fn iid(&self, ty: &Type) -> Fallible<[u8;16]> {
        match ty {
            Type::TypeDef(d,g) if d.kind()==TypeKind::Class=>self.iid(&self.default(*d)?),
            Type::TypeDef(d,g) if g.is_empty()=>guid(*d),
            Type::TypeDef(_,_)=>Ok(parameterized(&self.signature(ty)?)),
            Type::Object=>Ok([0xaf,0x86,0xe2,0xe0,0xb1,0x2d,0x4c,0x6a,0x9c,0x5a,0xd7,0xaa,0x65,0x10,0x1e,0x90]),
            _=>Err(format!("no IID for {ty:?}")),
        }
    }
    fn add(&mut self, ty: Type) -> Fallible<()> {
        match &ty {
            Type::TypeDef(d,g) => {
                if d.generics().count()!=g.len() { return Ok(()); }
                let key=Self::key(&ty); if self.types.contains_key(&key) { return Ok(()); }
                self.types.insert(key,ty.clone());
                if d.kind()==TypeKind::Class {
                    for interface in d.interface_impls() { self.add(interface.ty(g))?; }
                    if let Some(parent)=d.extends() { if parent!=TypeName::Object { self.add(Type::TypeDef(self.resolve(parent)?,vec![]))?; } }
                    for attr in ["StaticAttribute","ActivatableAttribute","ComposableAttribute"] {
                        for args in attrs(*d,attr) { if let Some(Value::TypeName(name))=args.first() { self.add(Type::TypeDef(self.resolve(*name)?,vec![]))?; } }
                    }
                }
                if d.kind()==TypeKind::Struct { for f in d.fields() { self.add_value(f.ty(Some(*d)))?; } }
                if matches!(d.kind(),TypeKind::Interface|TypeKind::Delegate) {
                    for method in d.methods().filter(|m|m.name()!=".ctor") {
                        let sig=method.signature(g); self.add_value(sig.return_type)?;
                        for p in sig.params { self.add_value(p)?; }
                    }
                }
            }
            _=>{},
        } Ok(())
    }
    fn add_value(&mut self, ty: Type) -> Fallible<()> {
        match &ty {
            // Class/interface references can travel as owned Object handles;
            // do not recursively project every method of every referenced class.
            Type::TypeDef(d,_) if matches!(d.kind(),TypeKind::Struct|TypeKind::Enum|TypeKind::Delegate)=>self.add(ty),
            Type::TypeDef(_,g) if !g.is_empty()=>self.add(ty),
            Type::WinrtArray(t)|Type::WinrtArrayRef(t)|Type::ConstRef(t)|Type::MutPtr(t,_)|Type::ConstPtr(t,_)=>self.add_value(*t.clone()),
            _=>Ok(()),
        }
    }
    fn name(&self, ty: &Type) -> Fallible<String> {
        self.names.get(&Self::key(ty)).cloned().ok_or_else(||format!("type not selected: {}",Self::key(ty)))
    }
    fn scalar(&self, ty: &Type) -> Fallible<String> {
        Ok(match ty {
            Type::Void=>return Err("void has no value representation".into()),
            Type::Bool=>"bool".into(),Type::Char|Type::U16=>"u16".into(),Type::I8=>"i8".into(),Type::U8=>"u8".into(),Type::I16=>"i16".into(),Type::I32=>"i32".into(),Type::U32=>"u32".into(),Type::I64=>"i64".into(),Type::U64=>"u64".into(),Type::F32=>"f32".into(),Type::F64=>"f64".into(),
            Type::Name(TypeName::GUID)=>"rt::Guid".into(),
            Type::TypeDef(d,_) if d.kind()==TypeKind::Enum=>self.scalar(&d.underlying_type())?,
            Type::TypeDef(d,_) if d.kind()==TypeKind::Struct=>self.name(ty)?,
            _=>return Err("array, pointer, or unresolved generic value is not yet projected".into()),
        })
    }
    fn is_object(ty: &Type) -> bool { matches!(ty,Type::Object) || matches!(ty,Type::TypeDef(d,_) if matches!(d.kind(),TypeKind::Class|TypeKind::Interface|TypeKind::Delegate)) }
    fn layout(&self, ty: &Type) -> Fallible<(usize,usize)> {
        match ty {
            Type::Bool|Type::U8|Type::I8=>Ok((1,1)),Type::Char|Type::I16|Type::U16=>Ok((2,2)),Type::I32|Type::U32|Type::F32=>Ok((4,4)),Type::I64|Type::U64|Type::F64=>Ok((8,8)),Type::Name(TypeName::GUID)=>Ok((16,4)),
            Type::TypeDef(d,_) if d.kind()==TypeKind::Enum=>self.layout(&d.underlying_type()),
            Type::TypeDef(d,_) if d.kind()==TypeKind::Struct=> {
                let mut size=0; let mut align=1;
                for f in d.fields() { let (s,a)=self.layout(&f.ty(Some(*d)))?; size=(size+a-1)/a*a+s; align=align.max(a); }
                Ok(((size+align-1)/align*align,align))
            }
            _=>Err("non-POD field requires ownership-aware struct projection".into()),
        }
    }
    fn projected(&self, ty: &Type) -> Fallible<String> {
        if Self::is_object(ty) { Ok("rt::Object".into()) } else if *ty==Type::String { Ok("text::Text".into()) } else { self.scalar(ty) }
    }
    fn generate(mut self, includes: &[String], package: &str) -> Fallible<(String,Vec<serde_json::Value>)> {
        for include in includes {
            let mut matched=false;
            let defs: Vec<_>=self.reader.items().filter_map(|i|if let Item::Type(d)=i{Some(d)}else{None}).collect();
            for d in defs {
                if full(d)==*include || include.strip_suffix(".*").map(|ns|d.namespace()==ns || d.namespace().starts_with(&format!("{ns}."))).unwrap_or(false) {
                    matched=true; self.add(Type::TypeDef(d,vec![]))?;
                }
            }
            if !matched { return Err(format!("selection {include} did not match any metadata type")); }
        }
        let mut used=BTreeSet::new();
        for (key,ty) in &self.types {
            let Type::TypeDef(d,g)=ty else {continue};
            let mut name=d.name().to_string();
            if !g.is_empty() { name.push('_'); name.push_str(&g.iter().map(|t|Self::key(t).replace(['.','<','>',','],"_")).collect::<Vec<_>>().join("_")); }
            if !used.insert(name.clone()) { name=key.replace(['.','<','>',','],"_"); used.insert(name.clone()); }
            while name.contains("__") { name=name.replace("__","_"); }
            name=name.trim_end_matches('_').to_string();
            self.names.insert(key.clone(),name);
        }
        let mut out=format!("// Generated by cpc-bindgen --winmd. DO NOT EDIT.\n// {package}: Windows x64 ABI. See MANIFEST.json for provenance and coverage.\nimport \"winrt/runtime\" as rt;\nimport \"stdlib/result\" as result;\nimport \"stdlib/text\" as text;\n\n");
        let types: Vec<_>=self.types.values().cloned().collect();
        for ty in &types { self.emit_type(ty,&mut out)?; }
        Ok((out,self.reports))
    }
    fn emit_type(&mut self, ty: &Type, out: &mut String) -> Fallible<()> {
        let Type::TypeDef(d,g)=ty else {return Ok(())}; let name=self.name(ty)?;
        let mut report=serde_json::json!({"metadata":Self::key(ty),"name":name,"kind":format!("{:?}",d.kind()),"methods":[]});
        writeln!(out,"// {}",Self::key(ty)).unwrap();
        if d.kind()==TypeKind::Enum {
            let underlying=self.scalar(&d.underlying_type())?; writeln!(out,"type {name} = {underlying};").unwrap();
            for field in d.fields() { if let Some(c)=field.constant() {
                let value=match c.value() {Value::I32(v)=>v.to_string(),Value::U32(v)=>format!("{v}u32"),_=>return Err("unsupported enum backing constant".into())};
                writeln!(out,"const {}_{}: {name} = {value} as {underlying};",snake(&name),snake(field.name())).unwrap();
            }}
        } else if d.kind()==TypeKind::Struct {
            match self.layout(ty) {
                Ok((size,align))=> {
                    writeln!(out,"#[repr(C)]\nstruct {name} {{").unwrap();
                    for f in d.fields() { writeln!(out,"    {}: {},",snake(f.name()),self.scalar(&f.ty(Some(*d)))?).unwrap(); }
                    writeln!(out,"}}\nconst {}_size: usize = {size};\nconst {}_alignment: usize = {align};",snake(&name),snake(&name)).unwrap();
                }
                Err(reason)=> { report["skipped"]=reason.clone().into(); writeln!(out,"// SKIPPED {name}: {reason}").unwrap(); }
            }
        } else {
            if matches!(d.kind(),TypeKind::Interface|TypeKind::Delegate) {
                for (index,m) in d.methods().filter(|m|m.name()!=".ctor").enumerate() {
                    writeln!(out,"const {}_{}_slot: usize = {};",snake(&name),snake(&method_name(m)),index+if d.kind()==TypeKind::Delegate{3}else{6}).unwrap();
                }
            }
            let iid=self.iid(ty);
            if let Ok(id)=iid {
                writeln!(out,"fn {}_iid() -> rt::Guid {{ return {}; }}",snake(&name),guid_literal(&id)).unwrap();
                report["iid"]=guid_string(&id).into();
                writeln!(out,"struct {name} {{ _object: rt::Object }}\nimpl {name} {{\n    fn query(value: rt::Object) -> result::Result[{name}, rt::Error] {{\n        match value.query({}_iid()) {{\n            result::Result::Ok(o) => {{ return result::Result[{name}, rt::Error]::Ok({name} {{ _object: o }}); }}\n            result::Result::Err(e) => {{ return result::Result[{name}, rt::Error]::Err(e); }}\n        }}\n    }}\n    fn object(this) -> rt::Object {{ return this._object.clone(); }}\n    fn raw(this) -> *u8 {{ return this._object.raw(); }}\n    fn clone(this) -> {name} {{ return {name} {{ _object: this._object.clone() }}; }}",snake(&name)).unwrap();
            } else { writeln!(out,"struct {name} {{}}\nimpl {name} {{").unwrap(); }
            if d.kind()==TypeKind::Class {
                self.emit_class(*d,&name,out,&mut report)?;
            } else {
                if d.kind()==TypeKind::Delegate {
                    if let Some(invoke)=d.methods().find(|m|m.name()=="Invoke") {
                        match self.emit_delegate(invoke,g,&name,out) {
                            Ok(())=>report["callback"]="emitted".into(),
                            Err(reason)=>report["callback_skipped"]=reason.into(),
                        }
                    }
                }
                for (index,m) in d.methods().filter(|m|m.name()!=".ctor").enumerate() {
                    let slot=index+if d.kind()==TypeKind::Delegate{3}else{6};
                    let status=self.emit_method(m,g,&name,slot,None,out);
                    if let Err(reason)=&status { writeln!(out,"    // SKIPPED {}: {reason}",method_name(m)).unwrap(); }
                    report["methods"].as_array_mut().unwrap().push(serde_json::json!({"name":method_name(m),"slot":slot,"status":status.as_ref().map(|_|"emitted").unwrap_or("skipped"),"reason":status.err()}));
                }
            }
            writeln!(out,"}}\n").unwrap();
        }
        self.reports.push(report); Ok(())
    }
    fn emit_class(&self, d: TypeDef, name: &str, out: &mut String, report: &mut serde_json::Value) -> Fallible<()> {
        // Expose metadata factory/static interfaces explicitly. Constructors are
        // generated only when metadata declares a default activation/composition.
        let mut seen=BTreeSet::new();
        for attr in ["StaticAttribute","ActivatableAttribute","ComposableAttribute"] {
            for values in attrs(d,attr) {
                if let Some(Value::TypeName(n))=values.first() {
                    let interface=Type::TypeDef(self.resolve(*n)?,vec![]); let iface=self.name(&interface)?;
                    let factory_name=format!("{}_factory",snake(&iface));
                    if seen.insert(factory_name.clone()) {
                        writeln!(out,"    fn {factory_name}() -> result::Result[{iface}, rt::Error] {{\n        match rt::activation_factory(\"{}\", {}_iid()) {{\n            result::Result::Ok(o) => {{ return result::Result[{iface}, rt::Error]::Ok({iface} {{ _object: o }}); }}\n            result::Result::Err(e) => {{ return result::Result[{iface}, rt::Error]::Err(e); }}\n        }}\n    }}",full(d),snake(&iface)).unwrap();
                    }
                    // CompositionType.Public = 2. Protected factories remain
                    // available for an outer implementation, not a plain new().
                    if attr=="ComposableAttribute" && values.get(1).and_then(|v|number(v).ok())==Some(2) && self.default(d).is_ok() {
                        let Type::TypeDef(fd,_) = interface else {continue};
                        for (slot,m) in fd.methods().enumerate() {
                            let sig=m.signature(&[]);
                            let params:Vec<_>=m.params().filter(|p|p.sequence()>0).collect();
                            if sig.params.len()==2 && sig.params[0]==Type::Object && params.len()==2 && params[1].flags().contains(ParamAttributes::Out) && Self::is_object(&sig.return_type) && seen.insert("new".into()) {
                                writeln!(out,"    fn new() -> result::Result[{name}, rt::Error] {{\n        match rt::compose(\"{}\", {}_iid(), {}, 0 as *u8) {{\n            result::Result::Ok(c) => {{ return {name}::query(c.object()); }}\n            result::Result::Err(e) => {{ return result::Result[{name}, rt::Error]::Err(e); }}\n        }}\n    }}",full(d),snake(&iface),slot+6).unwrap();
                            }
                        }
                    }
                } else if attr=="ActivatableAttribute" && self.default(d).is_ok() && seen.insert("new".into()) {
                    writeln!(out,"    fn new() -> result::Result[{name}, rt::Error] {{\n        match rt::activate(\"{}\") {{\n            result::Result::Ok(o) => {{ return {name}::query(o); }}\n            result::Result::Err(e) => {{ return result::Result[{name}, rt::Error]::Err(e); }}\n        }}\n    }}",full(d)).unwrap();
                }
            }
        }
        // Forward the default interface; other/versioned/base interfaces remain
        // available through typed Interface::query(object), never raw slot math.
        if let Ok(Type::TypeDef(interface,g))=self.default(d) {
            for (i,m) in interface.methods().enumerate() {
                let status=self.emit_method(m,&g,name,i+6,Some(Type::TypeDef(interface,g.clone())),out);
                report["methods"].as_array_mut().unwrap().push(serde_json::json!({"name":method_name(m),"slot":i+6,"status":status.as_ref().map(|_|"emitted").unwrap_or("skipped"),"reason":status.err()}));
            }
        }
        Ok(())
    }
    fn emit_method(&self, method: MethodDef, generics: &[Type], _owner: &str, slot: usize, _forward: Option<Type>, out: &mut String) -> Fallible<()> {
        let signature=method.signature(generics);
        let ret=&signature.return_type;
        let params:Vec<_>=method.params().filter(|p|p.sequence()>0).collect();
        if params.len()!=signature.params.len() { return Err("metadata parameter count mismatch".into()); }
        // Public composition factories can also take constructor arguments
        // (FontFamily is one example). Project the non-aggregated form: null
        // outer, and release the extra inner reference after the call.
        let composition = _owner.ends_with("Factory") && params.len()>=2
            && signature.params[params.len()-2]==Type::Object
            && params.last().unwrap().flags().contains(ParamAttributes::Out)
            && signature.params[params.len()-1]==Type::Object
            && Self::is_object(ret);
        let input_count=if composition {params.len()-2}else{params.len()};
        // Every method with complex byref/array output is retained in coverage
        // as unsupported until it has ownership-aware array/out projection.
        for (p,t) in params.iter().zip(&signature.params).take(input_count) {
            if p.flags().contains(ParamAttributes::Out) { return Err("additional out parameters: use a future multi-output projection".into()); }
            if matches!(t,Type::WinrtArray(_)|Type::WinrtArrayRef(_)|Type::MutPtr(_,_)|Type::ConstPtr(_,_)|Type::ConstRef(_)) { return Err("array or byref parameter is not yet projected".into()); }
        }
        let raw_name=method_name(method);
        let method_name=if let Some(p)=raw_name.strip_prefix("get_"){snake(p)}else if let Some(p)=raw_name.strip_prefix("put_"){format!("set_{}",snake(p))}else{snake(&raw_name)};
        let returns_void=*ret==Type::Void;
        let result_type=if returns_void{"rt::Status".into()}else{format!("result::Result[{}, rt::Error]",self.projected(ret)?)};
        let failure=|expr:&str|if returns_void{format!("return rt::Status {{ code: {expr}.code }};")}else{format!("return {result_type}::Err({expr});")};
        let mut declarations=vec!["this".to_string()]; let mut abi_types=vec!["*u8".to_string()]; let mut abi_args=vec!["this._object.raw()".to_string()]; let mut setup=String::new();
        for (i,(p,t)) in params.iter().zip(&signature.params).take(input_count).enumerate() {
            let pname=format!("{}_{}",snake(p.name()),i);
            if *t==Type::String {
                declarations.push(format!("{pname}: str")); abi_types.push("usize".into()); abi_args.push(format!("h_{i}.raw()"));
                writeln!(setup,"        let h_{i}: rt::HString = match rt::HString::new({pname}) {{ result::Result::Ok(v) => {{ v }}, result::Result::Err(e) => {{ {} }} }};",failure("e")).unwrap();
            } else if Self::is_object(t) {
                declarations.push(format!("{pname}: rt::Object")); abi_types.push("*u8".into());
                if *t==Type::Object { abi_args.push(format!("{pname}.raw()")); }
                else {
                    let iid=guid_literal(&self.iid(t)?); abi_args.push(format!("q_{i}.raw()"));
                    writeln!(setup,"        let q_{i}: rt::Object = match {pname}.query_nullable({iid}) {{ result::Result::Ok(v) => {{ v }}, result::Result::Err(e) => {{ {} }} }};",failure("e")).unwrap();
                }
            } else {
                let scalar=self.scalar(t)?; declarations.push(format!("{pname}: {scalar}"));
                if matches!(t,Type::TypeDef(d,_) if d.kind()==TypeKind::Struct) || *t==Type::Name(TypeName::GUID) {
                    let (size,_)=self.layout(t)?;
                    if [1,2,4,8].contains(&size) {
                        writeln!(setup,"        var copy_{i}: {scalar} = {pname};").unwrap();
                        abi_types.push(format!("u{}",size*8)); abi_args.push(format!("*(#addr_of(copy_{i}) as *u{})",size*8));
                    } else {
                        // Windows x64 requires caller-allocated aggregate
                        // temporaries to be 16-byte aligned, even for Rect.
                        let capacity=size+15;
                        writeln!(setup,"        var storage_{i}: [u8; {capacity}] = #zero::[[u8; {capacity}]]();\n        let aligned_{i}: *{scalar} = (((#addr_of(storage_{i}) as usize + 15) / 16) * 16) as *{scalar};\n        *aligned_{i} = {pname};").unwrap();
                        abi_types.push(format!("*{scalar}")); abi_args.push(format!("aligned_{i}"));
                    }
                } else { abi_types.push(scalar); abi_args.push(pname); }
            }
        }
        let mut tail=String::new();
        if composition {
            writeln!(setup,"        var inner: *u8 = 0 as *u8;").unwrap();
            abi_types.extend(["*u8".into(), "**u8".into()]);
            abi_args.extend(["0 as *u8".into(), "#addr_of(inner)".into()]);
        }
        if !returns_void {
            if Self::is_object(ret) || *ret==Type::String {
                writeln!(setup,"        var returned: usize = 0;").unwrap(); abi_types.push("*usize".into());
                tail=if *ret==Type::String { format!("        let owned: rt::HString = rt::HString::adopt(returned);\n        return owned.to_text();\n") } else { format!("        return {result_type}::Ok(rt::Object::adopt(returned as *u8));\n") };
            } else {
                let scalar=self.scalar(ret)?; self.layout(ret)?;
                writeln!(setup,"        var returned: {scalar} = #zero::[{scalar}]();").unwrap(); abi_types.push(format!("*{scalar}"));
                tail=format!("        return {result_type}::Ok(returned);\n");
            }
            abi_args.push("#addr_of(returned)".into());
        }
        // Buffer each complete method: an unsupported type must not leave half a method.
        let types=abi_types.join(", ");
        let mut code=format!("    // ABI slot {slot}: {}\n    fn {method_name}({}) -> {result_type} {{\n{setup}",method.name(),declarations.join(", "));
        writeln!(code,"        let call: fn({types}) -> i32 = rt::slot(this._object.raw(), {slot}) as fn({types}) -> i32;\n        let hr: i32 = call({});",abi_args.join(", ")).unwrap();
        if composition { writeln!(code,"        let inner_owner: rt::Object = rt::Object::adopt(inner);").unwrap(); }
        if returns_void { writeln!(code,"        return rt::Status {{ code: hr }};").unwrap(); }
        else {
            writeln!(code,"        if hr < 0 {{ return {result_type}::Err(rt::Error {{ code: hr }}); }}\n{tail}").unwrap();
        }
        writeln!(code,"    }}").unwrap(); out.push_str(&code); Ok(())
    }
    fn emit_delegate(&self, method: MethodDef, generics: &[Type], name: &str, out: &mut String) -> Fallible<()> {
        let signature=method.signature(generics);
        if signature.return_type!=Type::Void { return Err("delegate has non-void logical return".into()); }
        let mut high=Vec::new(); let mut abi=vec!["*u8".to_string()];
        let mut declarations=vec!["self: *u8".to_string()]; let mut args=Vec::new(); let mut setup=String::new();
        for (i,t) in signature.params.iter().enumerate() {
            high.push(self.projected(t)?);
            if Self::is_object(t) {
                abi.push("*u8".into()); declarations.push(format!("p{i}: *u8"));
                writeln!(setup,"        let v{i}: rt::Object = rt::Object::retain(p{i});").unwrap(); args.push(format!("v{i}"));
            } else if *t==Type::String { return Err("delegate string parameter needs borrowed HSTRING adapter".into()); }
            else {
                let scalar=self.scalar(t)?;
                if matches!(t,Type::TypeDef(d,_) if d.kind()==TypeKind::Struct) || *t==Type::Name(TypeName::GUID) { return Err("aggregate delegate input not yet projected".into()); }
                abi.push(scalar.clone()); declarations.push(format!("p{i}: {scalar}")); args.push(format!("p{i}"));
            }
        }
        high.push("*u8".into()); args.push("rt::delegate_context(self)".into());
        let high_types=high.join(", "); let abi_types=abi.join(", ");
        writeln!(out,"    fn new(on_invoke: fn({high_types}) -> rt::Status, on_invoke_ctx: *u8 = 0 as *u8, agile: bool = false) -> result::Result[{name}, rt::Error] {{\n        let invoke: fn({abi_types}) -> i32 = {name}::dispatch;\n        match rt::delegate({}_iid(), invoke as *u8, on_invoke as *u8, on_invoke_ctx, agile) {{\n            result::Result::Ok(o) => {{ return result::Result[{name}, rt::Error]::Ok({name} {{ _object: o }}); }}\n            result::Result::Err(e) => {{ return result::Result[{name}, rt::Error]::Err(e); }}\n        }}\n    }}\n    fn dispatch({}) -> i32 {{\n{setup}        let callback: fn({high_types}) -> rt::Status = rt::delegate_callback(self) as fn({high_types}) -> rt::Status;\n        let status: rt::Status = callback({});\n        return status.code;\n    }}",snake(name),declarations.join(", "),args.join(", ")).unwrap();
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test] fn vector_string_iid() { assert_eq!(guid_string(&parameterized("pinterface({913337e9-11a1-4345-a3a2-4e7f956e222d};string)")),"98b9acc1-4b56-532e-ac73-03d5291cca90"); }
    #[test] fn acronym_names() { assert_eq!(snake("GetUIElement"),"get_ui_element"); assert_eq!(snake("RequestedTheme"),"requested_theme"); }
    #[test] fn reserved_method_names() { assert_eq!(snake("Move"),"move_value"); assert_eq!(snake("Clone"),"clone_value"); assert_eq!(snake("get_Name"),"get_name"); }
    #[test] fn guid_byte_order() { assert!(guid_literal(&[0x12,0x34,0x56,0x78,0x9a,0xbc,0xde,0xf0,1,2,3,4,5,6,7,8]).starts_with("rt::Guid { a: 305419896u32, b: 39612 as u16, c: 57072 as u16")); }
}
