[package]
name = "facet_gallery_winui"
version = "0.0.1"
edition = "2026"
[build]
prebuild = false
[dependencies]
stdlib = "*"
facet = "*"
flex_layout = "*"
events = "*"
facet_winui = "*"
winui = "*"
winrt = "*"
