#!/usr/bin/env python3
"""gen_icons.py — the icon name -> codepoint table, generated from the font.

NOT part of the ledger bootstrap. This reads the font facet ships and emits one
constant per icon, and it is re-run only when the font is updated.

Why it is generated at all: a codepoint that is hand-typed can be wrong, render
correctly, and break only later. The symbol_spike found exactly that — `delete`
was typed as U+E872 (its position in the LEGACY Material Icons set, which the
full font still carries) instead of U+E92E. It drew a perfect trash can until
the font was subsetted from the name table, at which point it became a blank
square. A wrong attribute key and a wrong axis tag failed the same silent way.

So: nothing about this font is hand-typed. A constant per name means an unknown
icon is a COMPILE error, which is the whole reason the bundled set is the
recommended one — the `System` set is resolved by the OS at runtime and cannot
be checked at all.

  python3 tools/gen_icons.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "vendor", "facet", "assets")
FONT = "MaterialSymbolsOutlined"
OUT = os.path.join(ROOT, "vendor", "facet", "src", "icons.cplus")

# 67 names begin with a digit (`10k`, `123`, `3d_rotation`), which no identifier
# may. `n` for numeric, applied mechanically so the mapping stays predictable —
# `10k` is `n10k`, never `ten_k`.
DIGIT_PREFIX = "n"

# A name that collides with a keyword takes a trailing `_`. Also mechanical:
# `loop` is `loop_`, `move` is `move_`, and the comment on the line carries the
# real name either way.
KEYWORD_SUFFIX = "_"

LEXER = os.path.join(ROOT, "cplus-core", "src", "lexer.rs")


def keywords():
    """Every C+ keyword, read out of the compiler's own lexer.

    Not a hand-kept list. The first version of this script borrowed
    gen_contract's RESERVED table, which was written for the ledger member names and
    so had never needed `move` — and `move` is an icon. The compiler is the only
    authority on what it will not let you spell.
    """
    src = open(LEXER).read()
    return set(re.findall(r'^\s*"([a-z_][a-z_0-9]*)"\s*=>\s*TokenKind::', src, re.M))


KEYWORDS = set()


def spell(name):
    """The C+ constant name for an icon name."""
    if name[0].isdigit():
        return DIGIT_PREFIX + name
    if name in KEYWORDS:
        return name + KEYWORD_SUFFIX
    return name


def main():
    global KEYWORDS
    KEYWORDS = keywords()
    if not KEYWORDS:
        print("gen_icons: read no keywords out of the lexer. Nothing was written.",
              file=sys.stderr)
        raise SystemExit(1)
    src = os.path.join(ASSETS, FONT + ".codepoints")
    rows = []
    for line in open(src):
        if not line.strip():
            continue
        name, hexcp = line.split()
        rows.append((name, int(hexcp, 16)))
    rows.sort()

    seen, out, renamed = {}, [], []
    for name, cp in rows:
        ident = spell(name)
        if ident != name:
            renamed.append((name, ident))
        if ident in seen:
            print(f"gen_icons: `{ident}` is claimed by both `{seen[ident]}` and "
                  f"`{name}`. Nothing was written.", file=sys.stderr)
            raise SystemExit(1)
        seen[ident] = name
        out.append((ident, name, cp))

    o = ["// GENERATED by tools/gen_icons.py — DO NOT EDIT.\n",
         f"// {FONT}, Apache 2.0, from google/material-design-icons.\n",
         f"// {len(out)} names over {len(set(c for _i, _n, c in out))} glyphs; the\n",
         "// difference is aliases, which map onto the same codepoint.\n",
         "//\n",
         "// One constant per icon, so an unknown name is a compile error rather\n",
         "// than a blank square. Pass these to `symbol()`:\n",
         "//\n",
         "//     symbol(icons::home)\n",
         "//     symbol(icons::folder, size: 20.0f64, fill: 1.0f64)\n",
         "//\n",
         f"// {len(renamed)} names are not spellable as identifiers and are mapped:\n",
         "// a leading digit takes an `n` prefix, a C+ keyword takes a trailing\n",
         "// underscore. The keyword list is read out of cplus-core's lexer.\n\n"]
    for ident, name, cp in out:
        note = f"    // {name}" if ident != name else ""
        o.append(f"const {ident}: u32 = 0x{cp:04X}u32;{note}\n")

    with open(OUT, "w") as f:
        f.writelines(o)
    print(f"{len(out)} icons -> vendor/facet/src/icons.cplus "
          f"({len(renamed)} names remapped)")


if __name__ == "__main__":
    main()
