#!/usr/bin/env python3
"""gen_contract.py v2 — emit facet's generated contract as a WHOLE FILE.

maui-regen Phase 2. The v1 generator patched marker regions inside
hand-written files; that interleaving is what let 67 silently-no-op slots
drift in. v2 owns entire files instead (legal since EXT.1, the same-package
impl-extension feature): regeneration is file replacement, and facet.cplus
never carries generated code again.

Outputs:
  vendor/facet/src/contract.cplus   hook statics + registrars (backend-facing;
                                    apps never import this module) + one
                                    `impl core::Handle` extension block with
                                    the app-facing methods
  vendor/facet/docs/contract.md     the generated manifest — the answer to
                                    "does facet have X?" is one grep of this

Emission policy (the no-silent-slot rule): a slot is emitted ONLY when at
least one backend wires it with a verified backing. Everything else stays in
the MAP as ADOPT/FUTURE and lands here when its backing + probe arrive
(Phase 3). UNSUPPORTED-per-backend is recorded in the manifest, and a backend
impl may return false at runtime for a kind mismatch — but a slot with NO
backing anywhere emits NO method at all: a compile error at the call site
beats a silent no-op.

The SLOTS table below is the v2 seed: exactly the surface that was wired and
verified in v1 (minus set_is_visible — killed in favor of the hand-written
set_hidden, one visibility verb, per the MAP). Each entry is checked against
tools/maui_map.py so a slot the MAP dropped cannot be emitted.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import maui_map  # noqa: E402 — the curated MAP is the authority

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# slot name -> (facet value type, MAUI (Type, Member) provenance, appkit status note)
# appkit status: "wired" or "UNSUPPORTED: reason" — manifest content, and the
# wired flag is what permits emission at all.
SLOTS = [
    ("set_background_color", "Color", ("VisualElement", "Background"), "wired: setBackgroundColor:"),
    ("set_is_enabled", "bool", ("VisualElement", "IsEnabled"), "wired: setEnabled:"),
    ("set_is_focused", "bool", ("VisualElement", "IsFocused"), "wired: responder chain (hand impl — focus is a behavior, not a setter)"),
    ("set_is_read_only", "bool", ("InputView", "IsReadOnly"), "wired: setEditable: (inverted)"),
    ("set_opacity", "f64", ("VisualElement", "Opacity"), "wired: setAlphaValue:"),
    ("set_placeholder", "str", ("Entry", "Placeholder"), "wired: setPlaceholderString:"),
    ("set_progress", "f64", ("ProgressBar", "Progress"), "wired: setDoubleValue:"),
    ("set_text_color", "Color", ("Label", "TextColor"), "wired: setTextColor:"),
    ("set_title", "str", ("Button", "Text"), "wired: setTitle:"),
    ("set_minimum", "f64", ("Slider", "Minimum"), "wired: setMinValue:"),
    ("set_maximum", "f64", ("Slider", "Maximum"), "wired: setMaxValue:"),
    ("set_minimum_track_color", "Color", ("Slider", "MinimumTrackColor"), "wired: setTrackFillColor:"),
    ("set_maximum_track_color", "Color", ("Slider", "MaximumTrackColor"), "UNSUPPORTED on AppKit: NSSlider has no equivalent"),
    ("set_thumb_color", "Color", ("Slider", "ThumbColor"), "UNSUPPORTED on AppKit: NSSlider has no equivalent"),
    ("set_thumb_image", "str", ("Slider", "ThumbImageSource"), "UNSUPPORTED on AppKit: NSSlider has no equivalent"),
]

FNTY = {"Color": "core::Color", "f64": "f64", "bool": "bool", "str": "str", "i64": "i64"}


def map_status(prov):
    """The MAP's verdict for a (Type, Member) row — emission guard."""
    row = maui_map.OVERLAY.get(prov)
    if row:
        return row[0]
    return "ADOPT"  # default-adoptable band; the MAP would have dropped it otherwise


def emit_contract():
    lines = [
        "// GENERATED by tools/gen_contract.py — DO NOT EDIT.\n",
        "// facet's generated contract module: hook statics + registrars\n",
        "// (backend-facing — apps never import facet/contract) and the\n",
        "// app-facing Handle methods, attached through a same-package impl\n",
        "// extension (EXT.1). Regenerate with:\n",
        "//   python3 tools/gen_contract.py\n",
        "// The slot list is tools/gen_contract.py's SLOTS table, guarded by\n",
        "// the curated MAP (tools/maui_map.py). docs/contract.md is the\n",
        "// manifest twin of this file.\n",
        "\n",
        "import \"./facet\" as core;\n",
        "\n",
    ]
    for name, ty, prov, note in SLOTS:
        st = map_status(prov)
        if st == "DROP":
            raise SystemExit(f"slot {name} is DROP in the MAP; refusing to emit")
        f = FNTY[ty]
        up = name.upper()
        lines.append(f"// {prov[0]}.{prov[1]} — {note}\n")
        lines.append(f"static {up}_FN: fn(core::Handle, {f}) -> bool = #zero::[fn(core::Handle, {f}) -> bool]();\n")
        lines.append(f"fn {name}_fn(f: fn(core::Handle, {f}) -> bool) {{ {up}_FN = f; return; }}\n\n")
    lines.append("impl core::Handle {\n")
    for name, ty, prov, note in SLOTS:
        f = FNTY[ty]
        up = name.upper()
        lines.append(f"    // {prov[0]}.{prov[1]}. Chainable; a no-op on a miss, a kind\n")
        lines.append("    // without the property, or a backend that has not wired it.\n")
        lines.append(f"    fn {name}(this, v: {f}) -> core::Handle {{\n")
        lines.append(f"        let f: fn(core::Handle, {f}) -> bool = {up}_FN;\n")
        lines.append(f"        if f != (0 as fn(core::Handle, {f}) -> bool) {{ let _ok: bool = f(this, v); }}\n")
        lines.append("        return this;\n")
        lines.append("    }\n\n")
    lines.append("}\n")
    return "".join(lines)


def emit_manifest():
    lines = [
        "# facet contract manifest — GENERATED by tools/gen_contract.py\n\n",
        "Every generated contract slot, its type, its MAUI provenance, and its\n",
        "per-backend status. A slot absent from this file does not exist —\n",
        "calling it is a compile error, never a silent no-op. The hand-written\n",
        "contract (find/set_text/tree/size/observe_size/...) lives in\n",
        "facet.cplus and is documented in ref.md; this file is the generated\n",
        "band only.\n\n",
        "| slot | type | MAUI provenance | AppKit |\n",
        "|---|---|---|---|\n",
    ]
    for name, ty, prov, note in SLOTS:
        lines.append(f"| `{name}` | {ty} | {prov[0]}.{prov[1]} | {note} |\n")
    lines.append("\nGTK: nothing wired yet — every slot above is UNSUPPORTED there.\n")
    return "".join(lines)


def main():
    cp = os.path.join(ROOT, "vendor", "facet", "src", "contract.cplus")
    with open(cp, "w") as f:
        f.write(emit_contract())
    mp = os.path.join(ROOT, "vendor", "facet", "docs", "contract.md")
    with open(mp, "w") as f:
        f.write(emit_manifest())
    print(f"wrote {os.path.relpath(cp, ROOT)} ({len(SLOTS)} slots) + docs/contract.md")


if __name__ == "__main__":
    main()
