#!/usr/bin/env python3
"""gen_facet.py — bootstrap facet's portable contract + backend stubs from spec.

The loop this proves:
  MAUI spec (auto)  +  MAUI->facet MAP (curated once)  +  native binding (hand)
      -> generated facet contract (facet.cplus additions)
      -> generated backend impl  (facet_appkit.cplus additions)
      -> conformance check: every spec slot has a definite backend status.

Three inputs, cleanly separated by who owns them:
  SPEC   : the slot list, from MAUI's PublicAPI (tools/maui_spec.py). Automated.
  MAP    : MAUI name -> facet name + type, following naming_guideline.md (Swift
           style: role names, snake_case, callbacks not MVVM commands). Curated ONCE.
  NATIVE : facet slot -> the AppKit method that implements it, or UNSUPPORTED
           (no native equivalent). Hand-written per backend, small.

The contract itself reuses facet's existing seam: a `<SLOT>_FN` fn-pointer static
+ `set_<slot>_fn` registrar + a `Handle.<slot>()` method — exactly how SET_VALUE_FN
works today. A backend that doesn't register a slot leaves it null (soft); the
conformance check is what makes the contract hard: no slot may be silently absent.

Usage:
  python3 tools/gen_facet.py emit    # write generated fragments to plans/generated/
  python3 tools/gen_facet.py check   # conformance report for the MAP+NATIVE
"""
import json
import os
import sys

ROOT = "/Users/adel/Workspace/C+"
SPEC = f"{ROOT}/plans/portable-spec.generated.json"
OUT = f"{ROOT}/plans/generated"

# ---- The curated MAP + NATIVE for Slider (the two human-owned inputs) --------
# facet_name / facet_type follow naming_guideline.md. native = the AppKit method
# on the backing class, or None => UNSUPPORTED (no native equivalent; escape /
# custom-draw territory). `exists` marks slots facet already covers.
SLIDER = {
    "widget": "slider",
    "backing": "Slider",            # ak::Slider
    "maui_control": "Slider",
    "slots": [
        # facet_name            type     maui             native (NSSlider)          note
        ("value",              "f64",   "Value",          "set_double_value",  {"exists": True}),
        ("minimum",            "f64",   "Minimum",        "set_min_value",     {}),
        ("maximum",            "f64",   "Maximum",        "set_max_value",     {}),
        ("minimum_track_color","Color", "MinimumTrackColor","set_track_fill_color", {"approx": True}),
        ("maximum_track_color","Color", "MaximumTrackColor", None,            {}),  # no native
        ("thumb_color",        "Color", "ThumbColor",     None,               {}),  # no native
        ("thumb_image",        "str",   "ThumbImageSource", None,             {}),  # needs custom cell
        ("on_change",          "cb",    "ValueChanged",   "action",           {"exists": True}),
        ("on_drag_start",      "cb",    "DragStarted",    None,               {}),  # no native phase
        ("on_drag_end",        "cb",    "DragCompleted",  None,               {}),
    ],
    # MAUI slots intentionally dropped (MVVM duplicates -> facet uses callbacks):
    "dropped": ["DragStartedCommand", "DragCompletedCommand"],
}

FTYPE = {"f64": "f64", "Color": "Color", "str": "str"}          # facet.cplus scope
AK_FTYPE = {"f64": "f64", "Color": "facet::Color", "str": "str"}  # facet_appkit scope


def const_name(slot):
    return "SET_" + slot.upper() + "_FN"


def gen_contract(w):
    """facet.cplus additions: the portable contract for each mutator slot."""
    out = ["// ==== GENERATED by tools/gen_facet.py from the MAUI portable spec ====",
           f"// Contract slots for `{w['widget']}` (MAUI {w['maui_control']}). Each",
           "// backend must register every slot (see the conformance check).", ""]
    methods = []
    for name, ty, maui, native, flags in w["slots"]:
        if ty == "cb":
            continue  # events are construction-time callbacks, not registry mutators
        if flags.get("exists"):
            methods.append(f"    // {name}: already covered by the existing Handle surface")
            continue
        ct = const_name(name)
        ft = FTYPE[ty]
        out.append(f"static {ct}: fn(Handle, {ft}) -> bool = #zero::[fn(Handle, {ft}) -> bool]();")
        out.append(f"fn set_{name}_fn(f: fn(Handle, {ft}) -> bool) {{ {ct} = f; return; }}")
        methods.append(
            f"    // {name}  (MAUI {maui})\n"
            f"    fn set_{name}(this, v: {ft}) -> Handle {{\n"
            f"        let f: fn(Handle, {ft}) -> bool = {ct};\n"
            f"        if f != (0 as fn(Handle, {ft}) -> bool) {{ let _ok: bool = f(this, v); }}\n"
            f"        return this;\n    }}")
    out.append("")
    out.append("// Add these to `impl Handle`:")
    out += methods
    return "\n".join(out) + "\n"


def gen_appkit(w):
    """facet_appkit.cplus additions: native impls + registrations (or UNSUPPORTED)."""
    backing = w["backing"]
    out = ["// ==== GENERATED by tools/gen_facet.py — AppKit backend impls ====",
           f"// {w['widget']} -> ak::{backing}. Fill each native call; UNSUPPORTED = no",
           "// NSSlider equivalent (returns false; needs custom draw or .native()).", ""]
    regs = []
    for name, ty, maui, native, flags in w["slots"]:
        if ty == "cb" or flags.get("exists"):
            continue
        ft = AK_FTYPE[ty]
        if native is None:
            out.append(
                f"fn set_{name}_impl(h: facet::Handle, v: {ft}) -> bool {{\n"
                f"    // UNSUPPORTED on AppKit: NS{backing} has no {maui} equivalent.\n"
                f"    return false;\n}}")
        elif ty == "Color":
            out.append(
                f"fn set_{name}_impl(h: facet::Handle, v: facet::Color) -> bool {{\n"
                f"    let view: *u8 = h.view();\n"
                f"    if view == (0 as *u8) {{ return false; }}\n"
                f"    ak::{backing}::from_raw(view).{native}(ns_color(v));\n"
                f"    return true;\n}}")
        else:
            recv = f"ak::{backing}::from_raw(view)"
            out.append(
                f"fn set_{name}_impl(h: facet::Handle, v: {ft}) -> bool {{\n"
                f"    let view: *u8 = h.view();\n"
                f"    if view == (0 as *u8) {{ return false; }}\n"
                f"    {recv}.{native}(v);\n"
                f"    return true;\n}}")
        regs.append(f"    facet::set_{name}_fn(set_{name}_impl);")
    out.append("")
    out.append("// Add these to the backend install/register fn:")
    out += regs
    return "\n".join(out) + "\n"


def conformance(w):
    impl = uns = exists = 0
    rows = []
    for name, ty, maui, native, flags in w["slots"]:
        if flags.get("exists"):
            status = "PRE-EXISTING"; exists += 1
        elif native is None:
            status = "UNSUPPORTED (AppKit)"; uns += 1
        else:
            extra = " ~approx" if flags.get("approx") else ""
            status = f"impl -> NS{w['backing']}.{native}{extra}"; impl += 1
        rows.append((name, ty, status))
    return rows, impl, uns, exists


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    w = SLIDER
    if cmd == "emit":
        os.makedirs(OUT, exist_ok=True)
        open(f"{OUT}/facet_slider.contract.cplus", "w").write(gen_contract(w))
        open(f"{OUT}/facet_appkit_slider.impl.cplus", "w").write(gen_appkit(w))
        print(f"wrote {OUT}/facet_slider.contract.cplus")
        print(f"wrote {OUT}/facet_appkit_slider.impl.cplus")
    rows, impl, uns, exists = conformance(w)
    print(f"\nCONFORMANCE — {w['widget']} (MAUI {w['maui_control']}) on AppKit")
    print("-" * 62)
    for name, ty, status in rows:
        print(f"  {name:<22}{ty:<7}{status}")
    print("-" * 62)
    total = len(w["slots"])
    print(f"  {total} portable slots: {impl} implemented, {exists} pre-existing, "
          f"{uns} unsupported-on-AppKit")
    print(f"  dropped (MVVM dupes -> facet callbacks): {', '.join(w['dropped'])}")
    covered = impl + exists + uns
    print(f"\n  GREEN: {covered}/{total} slots have a definite status "
          f"(no silent gaps)." if covered == total
          else f"\n  RED: {total - covered} slots undecided.")


if __name__ == "__main__":
    main()
