"""Add a decorative search glyph to the pinned native TextBox template."""
import argparse
import json
import re
from pathlib import Path
root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
s = (root / 'playground/qwen_winui_preview/packages/Microsoft.WindowsAppSDK.WinUI.2.3.9/lib/native/Microsoft.UI/Themes/generic.xaml').read_text(encoding='utf-8-sig')
a = s.index('x:Key="DefaultTextBoxStyle"')
a = s.index('<ControlTemplate TargetType="TextBox">', a)
depth = 0
for m in re.finditer(r'</?ControlTemplate\b[^>]*>', s[a:]):
    depth += -1 if m.group().startswith('</') else 1
    if depth == 0:
        s = s[a:a + m.end()]
        break
else:
    raise ValueError('Unclosed TextBox template')
s = s.replace('<ControlTemplate TargetType="TextBox">', '<ControlTemplate xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" TargetType="TextBox">', 1)
s, count = re.subn(r'(<Grid.ColumnDefinitions>\s*)', r'\1<ColumnDefinition Width="32" />', s)
assert count == 1
s = s.replace('Grid.ColumnSpan="2"', 'Grid.ColumnSpan="3"')
s = s.replace('x:Name="DeleteButton" Grid.Row="1" Grid.Column="1"', 'x:Name="DeleteButton" Grid.Row="1" Grid.Column="2"')
for name in ('ContentElement', 'PlaceholderTextContentPresenter'):
    old = f'x:Name="{name}" Grid.Row="1" Grid.Column="0"'
    assert old in s
    s = s.replace(old, f'x:Name="{name}" Grid.Row="1" Grid.Column="1"')
s = s.replace('x:Name="PlaceholderTextContentPresenter" Grid.Row="1" Grid.Column="1" Grid.ColumnSpan="3"', 'x:Name="PlaceholderTextContentPresenter" Grid.Row="1" Grid.Column="1" Grid.ColumnSpan="2"')
pos = s.rfind('</Grid>')
s = s[:pos] + '<TextBlock x:Name="FacetSearchIcon" Grid.Row="1" Grid.Column="0" Text="&#xE721;" FontFamily="{ThemeResource SymbolThemeFontFamily}" FontSize="16" HorizontalAlignment="Center" VerticalAlignment="Center" IsHitTestVisible="False" AutomationProperties.AccessibilityView="Raw" />' + s[pos:]
s = ' '.join(s.split())
result = '// Copyright (c) Microsoft Corporation. All Rights Reserved.\n// Adapted from Windows App SDK 2.3.9 generic.xaml (MIT).\n// Generated by tools/generate_search_template.py.\nfn source() -> str {return ' + json.dumps(s) + ';}\n'
out = root / 'vendor/facet_winui/src/search_template.cplus'
if args.check:
    assert out.read_text(encoding='utf-8') == result
    print('PASS: pinned search template reproduction')
else:
    out.write_text(result, encoding='utf-8')
