#!/bin/sh
# The provenance proof for the facet package, runnable any time (clean or
# dirty tree). Invariant: the working-tree generated files are EXACTLY what the
# generator emits — a hand edit to a generated file is detected here (and
# overwritten, with a failure).
#
# This script had rotted: it checked `vendor/facet/src/contract.cplus` and
# `vendor/facet_appkit/src/contract_appkit.cplus`, which are pre-regen files
# that no longer exist, so `cp` failed on the first line and the gate never ran
# at all. The generated set is now the three files gen_contract.py writes plus
# the 38 control modules.
set -e
cd "$(dirname "$0")/.."
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/src" "$TMP/docs"
cp vendor/facet/src/*.cplus "$TMP/src/"
cp vendor/facet/docs/contract.md "$TMP/docs/"

python3 tools/gen_contract.py >/dev/null

fail=0
for f in vendor/facet/src/*.cplus; do
  b=$(basename "$f")
  # Only the generated ones: the hand-written modules say so on line 1.
  head -1 "$f" | grep -q "GENERATED by tools/gen_contract.py" || continue
  cmp -s "$f" "$TMP/src/$b" || {
    echo "FAIL: $f had drifted from generator output (now regenerated)" >&2
    fail=1
  }
done
cmp -s vendor/facet/docs/contract.md "$TMP/docs/contract.md" || {
  echo "FAIL: vendor/facet/docs/contract.md had drifted (now regenerated)" >&2
  fail=1
}

if grep -rn 'GEN:' vendor/facet/src/*.cplus vendor/facet_appkit/src/*.cplus >/dev/null 2>&1; then
  echo "FAIL: marker regions found" >&2; fail=1
fi

[ "$fail" = 0 ] && echo "contract provenance clean"
exit $fail
